name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
          cache: maven
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
        with:
          version: "1.6.1"
      - run: |
          dotnet nuget add source --username adsp-sdk-samples --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GovAlta/index.json"
          sed -i -r -e "s/TOKEN/${{ secrets.GITHUB_TOKEN }}/" apps/hello-world-spring/maven-settings.xml
          sed -i -r -e "s/TOKEN/${{ secrets.GITHUB_TOKEN }}/" apps/hello-world-spring-flux/maven-settings.xml
      - run: npm ci
      - name: Install
        shell: bash
        run: npx nx affected --target=install --base=${{ github.base_ref }}
      - name: Lint
        shell: bash
        run: npx nx affected --target=lint --base=${{ github.base_ref }}
      - name: Test
        shell: bash
        run: npx nx affected --target=test --base=${{ github.base_ref }}
      - name: Build
        shell: bash
        run: npx nx affected --configuration=production --target=build --base=${{ github.base_ref }}
